root: true
env:
  node: true
  es6: true
extends:
  "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
plugins:
  - "@typescript-eslint"
rules:
  no-console: error
  quotes:
    - error
    - double
  semi: error
  "@typescript-eslint/indent":
    - error
    - 2
  "@typescript-eslint/prefer-interface": off
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-empty-function": off
